### 1. Criar um array com 10 números inteiros aleatórios entre 1 e 50 e calcular a média e o desvio padrão

In [0]:
import numpy as np

arr = np.random.randint(1, 51, size = 10)

media_arr = loc(arr)

print(arr)

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<command-1489058988466844> in <cell line: 5>()
      3 arr = np.random.randint(1, 51, size = 10)
      4 
----> 5 media_arr = loc(arr)
      6 
      7 print(arr)

NameError: name 'loc' is not defined

### 2. Criar um array de 10 números aleatórios e calcular a raiz quadrada de todos os valores menores ou iguais a 0,5

In [0]:
import numpy as np
arr = np.random.rand(10)

for num in arr:
  if num <= 0.5:
    arr_quadrado = np.sqrt(arr)
    arr = arr_quadrado

print(arr)


[0.98515998 0.91989008 0.95803989 0.97378512 0.94350865 0.9786207
 0.99870222 0.99823538 0.91473894 0.95192327]


### 3. Criar uma matriz 3D de tamanho 3x3x3 com valores aleatórios e exibir o valor máximo de cada linha de cada matriz 2D dentro dessa matriz 3D

In [0]:
import numpy as np
arr = np.random.rand(3,3,3)



print("Matriz 3D:\n", arr)

Matriz 3D:
 [[[0.54647987 0.29630094 0.83253549]
  [0.195059   0.80395959 0.14275604]
  [0.61777331 0.51978826 0.33889115]]

 [[0.24592173 0.52285725 0.02165233]
  [0.31970148 0.1259373  0.10701759]
  [0.7296761  0.99557327 0.03707527]]

 [[0.95446199 0.31425806 0.70712546]
  [0.30313435 0.4187062  0.09363374]
  [0.71595443 0.55090976 0.57005433]]]


### 4. Criar uma matriz de tamanho 5x5 com valores aleatórios e subtrair a média de cada linha dessa matriz

### 5. Criar uma matriz de tamanho 4x4 com valores aleatórios e calcular a média e o desvio padrão das diagonais da matriz